#[non_exhaustive]
pub enum MiCommand {
    AdaTaskInfo,
    AddInferior,
    BreakInsert,
    DprintfInsert,
    BreakCondition,
    BreakCommands,
    BreakPasscount,
    BreakWatch,
    CatchAssert,
    CatchException,
    CatchHandlers,
    CatchLoad,
    CatchUnload,
    CatchThrow,
    CatchRethrow,
    CatchCatch,
    Disassemble,
    DataEvaluateExpression,
    DataListRegisterNames,
    DataListRegisterValues,
    DataListChangedRegisters,
    DataReadMemory,
    DataReadMemoryBytes,
    DataWriteMemory,
    DataWriteMemoryBytes,
    DataWriteRegisterValues,
    EnableTimings,
    EnvCd,
    EnvDir,
    EnvPath,
    EnvPwd,
    ExecContinue,
    ExecFinish,
    ExecInterrupt,
    ExecJump,
    ExecNext,
    ExecNextInstruction,
    ExecReturn,
    ExecRun,
    ExecStep,
    ExecStepInstruction,
    FileListExecSourceFile,
    FileListExecSourceFiles,
    FileListSharedLibraries,
    GdbExit,
    InferiorTtySet,
    InferiorTtyShow,
    InfoAdaExceptions,
    InfoGdbMiCommand,
    InfoOs,
    InterpreterExec,
    ListFeatures,
    ListTargetFeatures,
    ListThreadGroups,
    RemoveInferior,
    StackInfoDepth,
    StackInfoFrame,
    StackListArgs,
    StackListFrames,
    StackListLocals,
    StackListVariables,
    StackSelectFrame,
    SymbolListLines,
    SymbolInfoFunctions,
    SymbolInfoModuleFunctions,
    SymbolInfoModuleVariables,
    SymbolInfoModules,
    SymbolInfoTypes,
    SymbolInfoVariables,
    TargetDetach,
    TargetFileGet,
    TargetFilePut,
    TargetFileDelete,
    TargetFlashErase,
    ThreadInfo,
    ThreadListIds,
    ThreadSelect,
    TraceDefineVariable,
    TraceFind,
    TraceFrameCollected,
    TraceListVariables,
    TraceSave,
    TraceStart,
    TraceStatus,
    TraceStop,
    VarAssign,
    VarCreate,
    VarDelete,
    VarEvaluateExpression,
    VarInfoExpression,
    VarInfoPathExpression,
    VarInfoNumChildren,
    VarInfoType,
    VarListChildren,
    VarSetFormat,
    VarSetFrozen,
    VarSetVisualizer,
    VarShowAttributes,
    VarShowFormat,
    VarUpdate,
    EnablePrettyPrinting,
    EnableFrameFilters,
    VarSetUpdateRange,
    Complete,
}

impl MiCommand {
    pub fn as_str(self) -> &'static str {
        match self {
            MiCommand::AdaTaskInfo => "ada-task-info",
            MiCommand::AddInferior => "add-inferior",
            MiCommand::BreakInsert => "break-insert",
            MiCommand::DprintfInsert => "dprintf-insert",
            MiCommand::BreakCondition => "break-condition",
            MiCommand::BreakCommands => "break-commands",
            MiCommand::BreakPasscount => "break-passcount",
            MiCommand::BreakWatch => "break-watch",
            MiCommand::CatchAssert => "catch-assert",
            MiCommand::CatchException => "catch-exception",
            MiCommand::CatchHandlers => "catch-handlers",
            MiCommand::CatchLoad => "catch-load",
            MiCommand::CatchUnload => "catch-unload",
            MiCommand::CatchThrow => "catch-throw",
            MiCommand::CatchRethrow => "catch-rethrow",
            MiCommand::CatchCatch => "catch-catch",
            MiCommand::Disassemble => "disassemble",
            MiCommand::DataEvaluateExpression => "data-evaluate-expression",
            MiCommand::DataListRegisterNames => "data-list-register-names",
            MiCommand::DataListRegisterValues => "data-list-register-values",
            MiCommand::DataListChangedRegisters => "data-list-changed-registers",
            MiCommand::DataReadMemory => "data-read-memory",
            MiCommand::DataReadMemoryBytes => "data-read-memory-bytes",
            MiCommand::DataWriteMemory => "data-write-memory",
            MiCommand::DataWriteMemoryBytes => "data-write-memory-bytes",
            MiCommand::DataWriteRegisterValues => "data-write-register-values",
            MiCommand::EnableTimings => "enable-timings",
            MiCommand::EnvCd => "env-cd",
            MiCommand::EnvDir => "env-dir",
            MiCommand::EnvPath => "env-path",
            MiCommand::EnvPwd => "env-pwd",
            MiCommand::ExecContinue => "exec-continue",
            MiCommand::ExecFinish => "exec-finish",
            MiCommand::ExecInterrupt => "exec-interrupt",
            MiCommand::ExecJump => "exec-jump",
            MiCommand::ExecNext => "exec-next",
            MiCommand::ExecNextInstruction => "exec-next-instruction",
            MiCommand::ExecReturn => "exec-return",
            MiCommand::ExecRun => "exec-run",
            MiCommand::ExecStep => "exec-step",
            MiCommand::ExecStepInstruction => "exec-step-instruction",
            MiCommand::FileListExecSourceFile => "file-list-exec-source-file",
            MiCommand::FileListExecSourceFiles => "file-list-exec-source-files",
            MiCommand::FileListSharedLibraries => "file-list-shared-libraries",
            MiCommand::GdbExit => "gdb-exit",
            MiCommand::InferiorTtySet => "inferior-tty-set",
            MiCommand::InferiorTtyShow => "inferior-tty-show",
            MiCommand::InfoAdaExceptions => "info-ada-exceptions",
            MiCommand::InfoGdbMiCommand => "info-gdb-mi-command",
            MiCommand::InfoOs => "info-os",
            MiCommand::InterpreterExec => "interpreter-exec",
            MiCommand::ListFeatures => "list-features",
            MiCommand::ListTargetFeatures => "list-target-features",
            MiCommand::ListThreadGroups => "list-thread-groups",
            MiCommand::RemoveInferior => "remove-inferior",
            MiCommand::StackInfoDepth => "stack-info-depth",
            MiCommand::StackInfoFrame => "stack-info-frame",
            MiCommand::StackListArgs => "stack-list-args",
            MiCommand::StackListFrames => "stack-list-frames",
            MiCommand::StackListLocals => "stack-list-locals",
            MiCommand::StackListVariables => "stack-list-variables",
            MiCommand::StackSelectFrame => "stack-select-frame",
            MiCommand::SymbolListLines => "symbol-list-lines",
            MiCommand::SymbolInfoFunctions => "symbol-info-functions",
            MiCommand::SymbolInfoModuleFunctions => "symbol-info-module-functions",
            MiCommand::SymbolInfoModuleVariables => "symbol-info-module-variables",
            MiCommand::SymbolInfoModules => "symbol-info-modules",
            MiCommand::SymbolInfoTypes => "symbol-info-types",
            MiCommand::SymbolInfoVariables => "symbol-info-variables",
            MiCommand::TargetDetach => "target-detach",
            MiCommand::TargetFileGet => "target-file-get",
            MiCommand::TargetFilePut => "target-file-put",
            MiCommand::TargetFileDelete => "target-file-delete",
            MiCommand::TargetFlashErase => "target-flash-erase",
            MiCommand::ThreadInfo => "thread-info",
            MiCommand::ThreadListIds => "thread-list-ids",
            MiCommand::ThreadSelect => "thread-select",
            MiCommand::TraceDefineVariable => "trace-define-variable",
            MiCommand::TraceFind => "trace-find",
            MiCommand::TraceFrameCollected => "trace-frame-collected",
            MiCommand::TraceListVariables => "trace-list-variables",
            MiCommand::TraceSave => "trace-save",
            MiCommand::TraceStart => "trace-start",
            MiCommand::TraceStatus => "trace-status",
            MiCommand::TraceStop => "trace-stop",
            MiCommand::VarAssign => "var-assign",
            MiCommand::VarCreate => "var-create",
            MiCommand::VarDelete => "var-delete",
            MiCommand::VarEvaluateExpression => "var-evaluate-expression",
            MiCommand::VarInfoExpression => "var-info-expression",
            MiCommand::VarInfoPathExpression => "var-info-path-expression",
            MiCommand::VarInfoNumChildren => "var-info-num-children",
            MiCommand::VarInfoType => "var-info-type",
            MiCommand::VarListChildren => "var-list-children",
            MiCommand::VarSetFormat => "var-set-format",
            MiCommand::VarSetFrozen => "var-set-frozen",
            MiCommand::VarSetVisualizer => "var-set-visualizer",
            MiCommand::VarShowAttributes => "var-show-attributes",
            MiCommand::VarShowFormat => "var-show-format",
            MiCommand::VarUpdate => "var-update",
            MiCommand::EnablePrettyPrinting => "enable-pretty-printing",
            MiCommand::EnableFrameFilters => "enable-frame-filters",
            MiCommand::VarSetUpdateRange => "var-set-update-range",
            MiCommand::Complete => "complete",
        }
    }
}
